### ISSUE TITLE
Can't get 'Verify Ownership' working

### ISSUE THREAD

**Issue by joha78** [shannah/jdeploy#103]
Hey! 

Thank you for this great project!

I tried to get the 'Verify Ownership' feature working with my page, but unfortunately it gives me "Verification failed". It says that the hash could not be found. But I know it is there. Unfortunately there is no logging, what could be wrong. But my experiments showed that my page returns an 403 if the request has no "User-Agent" header. So, could you add a this header to the http-request?

With best regards
Jörg

**Comment by shannah** [comment]
Thanks.  That's probably the issue.  I'll look into it to try to verify.

**Comment by shannah** [comment]
This is fixed in 4.0.21.  The problem was the user-agent string, as you suspected.

This version should be available in a few minutes.
