### ISSUE TITLE
JDeply does not initialize correctly when one of the detected JAR files is corrupted

### ISSUE THREAD

**Issue by Oliver-Loeffler** [shannah/jdeploy#104]
As I was trying to get Scene Builder into npm registry via JDeploy, the command `jdeploy init` failed with an exception `java.util.zip.ZipException` and the file `package.json` was not created.

### Expected Behavior
* the error message ideally shows more detail, e.g. in which phase at which step something broke (e.g. the JAR file name during scanning for manifests) so that its a little bit easier to figure this out.
* The init process probably could continue, but JDeploy should inform (or warn) the user that one of the detected JAR files is broken
* JDeploy would not scan `src/test/resources` folders for JARs

### Current Behavior
The user will either see a dialog with an error message or read the exception message in the CLI.
![grafik](https://user-images.githubusercontent.com/22102800/227795283-26cc6b47-63bb-4369-9585-9d433a86d048.png)
Also JDeploy scanned all folders of the project, including resource directories, which in case for the tests, contained illegal JAR files.

### Steps to Reproduce

```commandline
md test
cd test
touch Empty.jar
jdeploy init
```

or:

```commandline
md test
cd test
echo TEST > Broken.jar
jdeploy init
```

Both cases will fail. The important thing is, the JAR must be somehow broken.

The problematic method is `JDeploy.findJarCandidates()`. The exception is raised at the attempt to open the 0-byte file with `new JarFile(f).getManifest()`.

### Your Environment
* JDK20, Win10
* NPM 9.5.0
* jdeploy@4.0.20

**Comment by shannah** [comment]
What is the use case for a zero byte jar file?

**Comment by shannah** [comment]
If you place your jars in a subdirectory it will only scan that subdirectory.  Not the root.
