### ISSUE TITLE
Switch from node-jre

### ISSUE THREAD

**Issue by tomasbjerre** [shannah/jdeploy#11]
Because `node-jre`:

* Only downloads Oracle JDK
* Seems to not be maintained anymore, based on the issues in the repo

https://github.com/schreiben/node-jre

I found `njre` that looks better:

https://github.com/raftario/njre

**Comment by tilmankamp** [comment]
This is a valid point, and as [njre](https://github.com/raftario/njre) is also better maintained, I'll discontinue this project now.

**Comment by nvuillam** [comment]
FYI, I released [java-caller](https://github.com/nvuillam/node-java-caller), which use [njre](https://github.com/raftario/njre) so can be compliant with any JRE/JDK java version

The module main goal is to allow to call java from custom node.js code, but it can also embed jars and create a CLI with a few manual actions (less automated than jdeploy, but can achieve some of its capabilities)

**Comment by shannah** [comment]
Cool.  Thanks for sharing.

**Comment by tomasbjerre** [comment]
I also created my own lib:
https://github.com/tomasbjerre/npm-java-runner

**Comment by shannah** [comment]
I have just published version 2.0.9, which changes it to use njre/adoptopenjdk.
