### ISSUE TITLE
On newer versions of node executing `jdeploy.js` fails with a syntax error: "Octal literals are not allowed"

### ISSUE THREAD

**Issue by JPercival** [shannah/jdeploy#117]
Here's the offending line:
https://github.com/shannah/jdeploy/blob/8e77742d820907aeb54a3922a32268037467058d/cli/src/main/resources/ca/weblite/jdeploy/jdeploy.js#L544

The suggested resolution is to use the octal format "0x755"

**Comment by shannah** [comment]
Thanks!  Will push out a new version (4.0.39) with this fixed.
