### ISSUE TITLE
zsh permission denied or Mac Sonoma 14.4.1

### ISSUE THREAD

**Issue by priand** [shannah/jdeploy#129]
I generated both the bundles and the installers on Mac 14.4.1 using `jdeploy package`. I can see the `.app` files generated but they fail to execute from the finder or a terminal. On the terminal, I get `zsh: permission denied`. The files are not locked, `chmod 755`, but can't fix the problem. I tried on both arm & x64 machines. I tried to change the app settings (accessibility), looked in the logs but found nothing.
Any idea?

**Comment by shannah** [comment]
Can you send a download link so i can take a look at it?

Steve Hannah
Web Lite Solutions Corp.

**Comment by priand** [comment]
Here it is: https://www.dropbox.com/scl/fo/6oz76xib02rjzf7uk7jcm/AB1yRaoFX_NN4bnPAnqWUdQ?rlkey=n37n4lw5o88a5qpkx82e7gdxy&st=3hb912ow&dl=0

**Comment by priand** [comment]
Thank you but don't loose your time. I missed the npm deployment, I was looking for an app that doesn't require that.

**Comment by shannah** [comment]
You don't need to deploy on npm.  You can deploy via github, with no need for npm at all
