### ISSUE TITLE
Bash completion script deploy

### ISSUE THREAD

**Issue by andrii-bodnar** [shannah/jdeploy#13]
I am using jDeploy for the **Simple Installation** - deploy to NPM and installation via `npm install -g <your-app>`

My command-line tool also has a Bash completion script.

Is there any way to deploy this script and then install it along with the app?

**Comment by shannah** [comment]
Probably you're looking for the [npm-scripts](https://docs.npmjs.com/misc/scripts) directive for the package.json, as this will allow you to run a script at various stages of your package's lifecycle, including installation.

Another way, would be to just do it from Java.  Embed the script into your app, then have your app detect whether it exists or not on first run, and copy it to the appropriate place if necessary.

**Comment by andrii-bodnar** [comment]
Thanks @shannah ! 

I will try to use the npm-scripts
