### ISSUE TITLE
App stops working if the release is deleted

### ISSUE THREAD

**Issue by halnuevemil** [shannah/jdeploy#132]
Hello.

Not sure if this is an error or deliberate or if this happens with GitHub only or with npm too, but if after installing an app you delete the release it doesn't affect just the update check, but it makes the app to not run at all after that, In fact it happens from the moment the launcher notice the deletion of the release. If you delete the release and then disconnect from internet before run the app then all is fine and the app launch correctly, since without internet it cannot even check if the release is there. If you then connect to internet and run the app  again it will notice the deletion and the app will not run, but even if you now disconnect from internet and run the app once again this time it will not launch despite it cannot check whether the release is there or not, it will not run again until you make a new release and run the launcher with internet connection.

Regards.
Ángel García.

**Comment by shannah** [comment]
Thanks.  i'll add a test case for that scenario and fix it.

**Comment by shannah** [comment]
Fixed in 4.0.51.

If you're using github releases for deployment, you'll have to create a new release of your app.
If you're using a jdeploy download page on jdeploy.com/~yourapp, then it should just work.
