### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by andrii-bodnar** [shannah/jdeploy#15]
The [latest](https://www.npmjs.com/package/jdeploy/v/1.0.21) version of the NPM package does not include all the tool updates (https://github.com/shannah/jdeploy/pull/7, https://github.com/shannah/jdeploy/pull/8, https://github.com/shannah/jdeploy/pull/10). 

Please update the NPM package.

**Comment by shannah** [comment]
These should be in the just-published 1.0.22

**Comment by andrii-bodnar** [comment]
@shannah thanks a lot for the fast response and update!
