### ISSUE TITLE
NOT AN ISSUE

### ISSUE THREAD

**Issue by theapache64** [shannah/jdeploy#23]
Thank you so much for maintaining this tool 😃

**Comment by theapache64** [comment]
![image](https://user-images.githubusercontent.com/9678279/153759291-9be3c4eb-4fcc-4b82-b326-0131f4827360.png)
this is awesome!

**Comment by shannah** [comment]
Thanks!  Glad you like it.

I tried to install your app and noticed that your "jar" property is in the wrong place in your package.json. It should be a property of the "jdeploy" object, but in yours it is in the root object.

Did you edit the package.json file manually, or did you use the jDeploy GUI?

**Comment by theapache64** [comment]
Yeah. that was a mistake from my side. I've been using `jdeploy` in many of my [projects](https://github.com/theapache64/gpm/blob/8c73437d7258279acc9da4d9385308f32a135bb0/package.json#L12).
