### ISSUE TITLE
Sign Windows Installer

### ISSUE THREAD

**Issue by uliar** [shannah/jdeploy#32]
I tried to install the demo and Windows Security stopped the installation by detecting the installer as Trojan:Script/Wacatac.B!ml

**Comment by shannah** [comment]
What version of Windows?  Do you have some sort of third party virus scanner?

**Comment by shannah** [comment]
Also, if you can share a screenshot of what this error looks like, I would be grateful.

**Comment by shannah** [comment]
Changed name of this issue since I can't reproduce it, but believe that it is probably an issue - and one solution is likely to sign the Windows installer.

**Comment by electronstudio** [comment]
I believe it’s not just about signing; windows defender will flag files as malware until a certain number of windows users have completed the install and clicked “this is not malware”.

**Comment by FelipeAumannRS** [comment]
One of our users recently brought this to our attention:

![image](https://github.com/shannah/jdeploy/assets/26864246/642d34ef-5215-4125-a821-f32b0147bec8)
Is there a possible solution to address this behavior, or is it more likely to be an issue related to JDeploy?

**Comment by shannah** [comment]
Note: The jDeploy installer is now signed by an EV certificate so you should no longer see any warnings when running the installer.

**Comment by FelipeAumannRS** [comment]
Outstanding!!! What a great addition to jDeploy!!!
