### ISSUE TITLE
Ubuntu icon not appearing on dock for JavaFX apps

### ISSUE THREAD

**Issue by shannah** [shannah/jdeploy#53]
This issue occurs for both the jfxcentral and JavaFX Ensemble.  When opening the app, the icon appears on the Ubuntu dock while the update progress dialog is showing, but when the app actually loads, the icon appears blank.

This does not occur with the SwingSet demo.

Need to investigate.  Both the SwingSet demo and JavaFX ensemble demo use Java 11, but they use different distributions. JavaFX ensemble uses a jre11+fx distribution from Azul, whereas SwingSet uses just jre11.  

The problem could either be related to JavaFX (i.e. JavaFX does something that causes a problem with the icon), or it could be related to the distribution difference.   Easy way to determine if it is the distribution is to change SwingSet to use jre11+fx.  If it still seems to work, then likely its something with JavaFX....

**Comment by shannah** [comment]
Experiment 1: Tried running using java directly:
java -jar jfxcentral-1.0.jar

Got same result: Taskbar icon is blank.

I was using the same Azul jre17+fx distribution for this test.

**Comment by shannah** [comment]
I have confirmed that adding an icon to the stage explicitly will work around this issue, and display the icon correctly on Ubuntu. 

See [the ensemble8 demo](https://github.com/shannah/javafx-ensemble8/blob/97615ef48abeb80c1b8faf414a05ef51a80b05e1/src/main/java/ensemble/EnsembleApp.java#L357) for an example.

 Not sure if this is a bug in JavaFX, or the Azul distributions yet, or if this is expected behaviour.  Also don't know if there is a way to provide a default icon using System properties.

@dlemmermann Do you know if there is a system property available to set the default Stage icon?  I haven't been able to find anything.

**Comment by dlemmermann** [comment]
Looks like it is not 100% reliable.

**Comment by shannah** [comment]
For now, then, the best I can do is add this to the documentation, and perhaps add a notice in the jdeploy GUI when you add an icon to point you to the workaround.

It is possible that this is Azul-specific, and that it could be resolved by switching to another distribution.  I plan to add support for other distributions anyways, but Azul is nice because they provide the jre+fx and jdk+fx distros, which I haven't seen anywhere else - i.e. I'll have to roll my own JavaFX solution.

**Comment by shannah** [comment]
I've added a note about this in the developer guide.

> NOTE: If you are using JavaFX you should also add your icon to your app's Stage using `stage.getIcons().add(...)` as there is a https://github.com/shannah/jdeploy/issues/53[bug] in Ubuntu that will cause the app's icon to appear blank in the taskbar otherwise.

I'm going to close this issue as I don't think there's much that can be done here.
