### ISSUE TITLE
Splash screen does not disappear

### ISSUE THREAD

**Issue by dlemmermann** [shannah/jdeploy#62]
When using a splash screen it shows up nicely but then never disappears.

**Comment by shannah** [comment]
Looks like you have to use the SplashScreen API in your app to hide the splashscreen when all your stuff is loaded.
Funny, I set up a few sample apps myself with the splashscreen and it seemed to hide on its own - though I expected to have to explicitly close it with the API. 
https://docs.oracle.com/en/java/javase/13/docs/api/java.desktop/java/awt/SplashScreen.html

E.g.

~~~~
SplashScreen splash = SplashScreen.getSplashScreen();
if (splash != null) {
    splash.close();
}
~~~~

**Comment by dlemmermann** [comment]
Yes, that solved the issue.
