### ISSUE TITLE
[BUG] cannot download jre 11

### ISSUE THREAD

**Issue by BlackHole1** [shannah/jdeploy#77]
1. `jdeploy` use `njre`.
2. `njre` use `api.adoptopenjdk.net/v2`
3. `api.adoptopenjdk.net/v2` is not available

gist: https://gist.github.com/BlackHole1/f03751a7c38bc79d9484828527a78e7c

**Fix suggestions**

Replace `njre` with `node-java-connector`

**Related issues**
* https://github.com/crowdin/crowdin-cli/issues/467
* https://github.com/electron/electronjs.org-new/issues/250

> This is an upstream bug

**Comment by shannah** [comment]
jDeploy 3+ uses zulu as the default provider, and the CI script indicates that crowdin uses jDeploy 3.2.0 for current builds.
It is likely that this bug was produced by an old version of crowdin which uses an older version of jDeploy.
