### ISSUE TITLE
For all jDeploy users - Help ask NPM to increase payload size

### ISSUE THREAD

**Issue by FelipeAumannRS** [shannah/jdeploy#82]
There's a limit on the size of the jar you can upload to NPM, 256Mb (which is the max payload size).

I've requested NPM to increase the max payload size. Please give it some support by upvoting the topic - it may become a feature in the near future, which I deeply believe to be very rewarding for those using jDeploy:
https://github.com/npm/feedback/discussions/816

**Comment by shannah** [comment]
Ok.
I am currently working on support for hosting your apps on github using github releases.  After that I'll be addressing self hosting.  Both would help address your size issues.

**Comment by FelipeAumannRS** [comment]
@shannah 
Sounds awesome! Can't wait for it!

Btw, I'm unable to use a few jars because of this limitation. Is there any expectation for that to be up and running?

**Comment by shannah** [comment]
Github hosting is already in alpha on master.  I'm just working out a few kinks.  Should be ready for ga next week if all goes well.

**Comment by FelipeAumannRS** [comment]
@shannah 
Does it have any documentation already? Can I use the GUI in order to test it? Or add some configuration in package.json

**Comment by shannah** [comment]
No documentation yet.  That is most if what is remaining to do.

It uses github actions to publish releases.  You can publish on release or on merge.  The publish on release would work similar to npm except it uses github releases instead.  

The publish on merge option would allow you to distribute an app that is auto synced with a particular branch of your repo so you need to do to release an updates is git push.

**Comment by FelipeAumannRS** [comment]
@shannah 
Sounds promising

Last, how can I know if this functionality is ready for usage? Will it be posted somewhere? Is there a mailer email I can subscribe to get jDeploy latest news?

**Comment by shannah** [comment]
I will make an announcement in the jdeploy newsletter.
https://jdeploy.substack.com/

**Comment by FelipeAumannRS** [comment]
Thank you, just got the annual subscription (as soon Nume starts monetizing, I'll make sure to "show my undying gratitude").

**Comment by shannah** [comment]
Thank you so much for your support.  It is appreciated and motivating.
