### ISSUE TITLE
Trojan in Windows Installer?

### ISSUE THREAD

**Issue by JimT787** [shannah/jdeploy#95]
Got the Github private repo --> public release repo working and used installer for Mac succussfully.  However, the Win64 installer from the public releases repository will not run and antivirus is saying a Severe Trojan is in the installer package.  I attached the screenshot.  I reran the release build and got the same result.

![AntivirusWarning](https://user-images.githubusercontent.com/98830368/218520721-0e47bb23-c515-4864-87b0-b438b1adba92.png)

**Comment by JimT787** [comment]
That's what I was hoping.  Thank you!

**Comment by shannah** [comment]
This issue is fixed in version 4.0.17.

You will need to create a new release of your app, in order to benefit from this.
Note: You may also need to close and reopen your browser before downloading your new release just to give it a "fresh" start.

**Comment by shannah** [comment]
The Windows installer is now signed (by my company - Web Lite Solutions).  While this doesn't guarantee that Windows won't mistake it for a virus, my tests so far have been promising.  The machine that was complaining before about it being a virus no longer complains.  From what I have read, having the exe signed makes it much less likely that Windows will mistake it for a virus.

**Comment by JimT787** [comment]
That is terrific!  Thank you!

 

Jim
