### ISSUE TITLE
Creating Github release to public repo fails due to "jDeploy" tag already exists in public repo

### ISSUE THREAD

**Issue by JimT787** [shannah/jdeploy#96]
When I create a new release in the private repo, the Github action seems to create 3 workflow processes.  They all seem to want to create a 'jdeploy' tag in the public releases repo, so they fail if I don't go to the public repo and delete the 'jdeploy' tag there every time I create a new release.  In addition, when I do delete the 'jdeploy' tag in the public repo, 2 of the 3 workflow processes still fail anyway because once one of the processes creates that tag, the other 2 process fail.  

Does it always spawn these 3 processes or am I doing something wrong?  

Thanks in advance if there is a solution

![Always-spawns-3-processes](https://user-images.githubusercontent.com/98830368/218523023-ae61cdf1-cbf4-42f5-b636-1b8a9d734a30.png)

![2-of-3-fail](https://user-images.githubusercontent.com/98830368/218523022-27835e81-8c28-4587-9756-f240d7660dbb.png)

![jdeploy-tag-already-exists](https://user-images.githubusercontent.com/98830368/218523025-6e6c2fb0-e50f-4770-a2dd-52fee40668cc.png)

**Comment by shannah** [comment]
The error message just before that provides a clue.  Seems you need to create a personal access token (classic), as fine grained personal access tokens can't be used for some APIs.

This pages talks about these limitations.

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by JimT787** [comment]
Ok--thanks again!
