### ISSUE TITLE
Github workflow installer package not producing desired application icon

### ISSUE THREAD

**Issue by JimT787** [shannah/jdeploy#97]
I have an 'icon.png' in the same root folder with 'package.json' and it is 512x512 as recommended in the jDeploy documentation.

The installer package installs properly, but only produces the generic icon on the desktop.

I included a screenshot of the Github code page to demonstrate this.  This is an installer package produced with a Github workflow and I tried the installer on Mac and Windows with the same effect--generic icon.

Maybe I'm doing something wrong?  I did not try to produce an installable package using the npm method.

**Comment by shannah** [comment]
Are you downloading it from the jdeploy download page or the github release page?

**Comment by shannah** [comment]
I have a few ideas on what is going on here, but probably won't be able to look at this until next weekend.

**Comment by JimT787** [comment]
No worries—thank you for the update!

 

Jim

**Comment by shannahcloudbeds** [comment]
@pkriens Sorry, just noticed this message now.

The github support is more recent.  npm is simpler, and, I suppose, more proven by the fact that I have been using it since v1.0, and github is just since 4.0.  That said, the GitHub support provides a few nice things, like the ability to have branch-based releases, and turn-key integration with github actions for releases.

**Comment by electronstudio** [comment]
I have same issue as @JimT787 and @pkriens . Was a solution ever found?

**Comment by shannah** [comment]
@electronstudio Can you share a link to your repo (if available) or just your download page (if repo not available)?  I'd like to take a look at what is going on there.

**Comment by electronstudio** [comment]
thanks, i'll email it to you

**Comment by shannah** [comment]
This issue is fixed now.  If you run the installer again, it should pick up your latest icon. and splash screen.
