### ISSUE TITLE
Application will not run if not connected to the internet

### ISSUE THREAD

**Issue by JimT787** [shannah/jdeploy#98]
I produced a small test application using npm as the deployment repository at https://www.jdeploy.com/~jimjdeploytest which installs and runs nicely; however it will only run if the computer is connected to the internet.

I was having problems earlier today trying to double-click the icon on the desktop--it would not run.  Later in the day, it decided to run.  I do have some weird internet issues here at the house...

I decided to test by double-clicking the icon with wifi enabled (connected to internet) and wifi disabled (not connected to internet).  It would only run if connected to the internet.

Perhaps the jdeploy application launcher is trying to check for updates and if it cannot connect to the internet, it just fails and stops launching the application altogether with no message?

**Comment by shannah** [comment]
This is true.  Right now it checks for updates on launch and will fail if that fails.  I'll add this to my list of things to improve.

**Comment by electricsam** [comment]
Just wondering if any updates were made to this.  I am making an app that will be used on NOAA ocean vessels that have no Internet access. JDeploy seemed like the perfect solution to solve issues we have with our current application.  Namely: cross-platform, easy to use for non technical personnel, able to run from non-admin accounts.   Unfortunately, this is a showstopper for me.

**Comment by shannah** [comment]
Will be part of 4.0.34.  When that is released, you'll just need to reinstall your app, and it will work offline.
